name: gdg_algiers_events_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  transparent_image: ^2.0.0
  device_preview: ^1.1.0
  flutter_carousel_widget: ^1.0.5
  url_launcher: ^6.1.0
  card_swiper: ^2.0.3
  table_calendar: ^3.0.5
  youtube_player_flutter: ^8.1.2
  hexcolor: ^2.0.7
  smooth_page_indicator: ^1.0.0+2
  simple_gradient_text: ^1.2.3
  dio_helper: ^1.1.19
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: 
  uses-material-design:
    true
    # assets:
    # To add assets to your application, add an assets section, like this:
  assets:
    - assets/photos/
    - assets/icons/
    - assets/icons/time1.svg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
